spring:
  datasource:
    url: jdbc:mysql://qzhy-hz.com:3306/Vue_js?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8181
  servlet:
    context-path: /spring-books

